contentColumnType: text
fieldGroup: fc416cd1-5f2d-4596-963a-9e3fa137689e
handle: paragraph
instructions: ''
name: Paragraph
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: '1'
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
