enableVersioning: true
handle: libraryAudio
name: 'Library Audio'
propagationMethod: all
siteSettings:
  16577b9f-37cc-4fe5-ab94-920c3ae062b4:
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'library/audio/{slug}'
type: channel
